### ISSUE TITLE
main_demo.py in not working correctly

### ISSUE THREAD

**Issue by bardhh** [Shaddadi/veritex#14]
The following image is generated: 
![image22](https://user-images.githubusercontent.com/28318161/163447334-72c07b5f-f144-4da7-8787-7b7738071ce4.png)

When running main_demo.py, the following error is reported for each iteration: 

Process Process-375:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/veritex/veritex/methods/worker.py", line 66, in main_func
    self.state_spawn_depth_first(tuple_state)
  File "/veritex/veritex/methods/worker.py", line 368, in state_spawn_depth_first
    self.state_spawn_depth_first(next_tuple_states[0])
  File "/veritex/veritex/methods/worker.py", line 368, in state_spawn_depth_first
    self.state_spawn_depth_first(next_tuple_states[0])
  File "/veritex/veritex/methods/worker.py", line 368, in state_spawn_depth_first
    self.state_spawn_depth_first(next_tuple_states[0])
  [Previous line repeated 8 more times]
  File "/veritex/veritex/methods/worker.py", line 348, in state_spawn_depth_first
    self.collect_results(next_tuple_states[0][0])
  File "/veritex/veritex/methods/worker.py", line 333, in collect_results
    unsafe_inputs = self.dnn.backtrack(vfl)
  File "/veritex/veritex/networks/ffnn.py", line 79, in backtrack
    elements = np.dot(np.dot(As_unsafe,vfl_set.M), vfl_set.vertices.T) + np.dot(As_unsafe, vfl_set.b) +ds_unsafe
TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations.
Process Process-378:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/veritex/veritex/methods/worker.py", line 66, in main_func
    self.state_spawn_depth_first(tuple_state)
  File "/veritex/veritex/methods/worker.py", line 368, in state_spawn_depth_first
    self.state_spawn_depth_first(next_tuple_states[0])
  File "/veritex/veritex/methods/worker.py", line 368, in state_spawn_depth_first
    self.state_spawn_depth_first(next_tuple_states[0])
  File "/veritex/veritex/methods/worker.py", line 368, in state_spawn_depth_first
    self.state_spawn_depth_first(next_tuple_states[0])
  [Previous line repeated 8 more times]
  File "/veritex/veritex/methods/worker.py", line 348, in state_spawn_depth_first
    self.collect_results(next_tuple_states[0][0])
  File "/veritex/veritex/methods/worker.py", line 333, in collect_results
    unsafe_inputs = self.dnn.backtrack(vfl)
  File "/veritex/veritex/networks/ffnn.py", line 79, in backtrack
    elements = np.dot(np.dot(As_unsafe,vfl_set.M), vfl_set.vertices.T) + np.dot(As_unsafe, vfl_set.b) +ds_unsafe
TypeError: Concatenation operation is not implemented for NumPy arrays, use np.concatenate() instead. Please do not rely on this error; it may not be given on all Python implementations.

**Comment by Shaddadi** [comment]
Bugs have been fixed
